Repository snek-at/front, pull requests merged in 2020-08, with the labels that each got.

#116 Migrate snekclientv2 aa1 to implement 1
  package.json
  src/components/atoms/SearchBar/index.jsx
  src/store/actions/authActions.js
  src/store/actions/generalActions.js
  src/store/actions/userActions.js
  src/store/reducers/generalReducers.js
  versions.txt
Labels: enhancement

#122 Improve overview aa1 to implement 1
  package.json
  src/components/atoms/charts/Calendar3D/index.jsx
  src/components/atoms/charts/LatestActivity/index.jsx
  src/components/organisms/ProfileInfo/index.jsx
  src/components/organisms/ProfileInfo/profileinfo.scss
  src/components/organisms/SoftwareTabs/index.jsx
  src/components/organisms/SoftwareTabs/softwaretabs.scss
  versions.txt
Labels: bug, enhancement

#123 Improve settings ba1 to implement 1
  src/components/pages/SettingsPage/index.jsx
Labels: bug
