Repository snek-at/front, pull requests merged in 2020-06, with the labels that each got.

#13 Improve readme aa1 to master
  README.md
Labels: documentation

#27 Add atoms charts aa1 to implement 1
  src/components/atoms/charts/Calendar2D/calendar2d.scss
  src/components/atoms/charts/Calendar2D/index.jsx
  src/components/atoms/charts/Calendar3D/calendar3d.scss
  src/components/atoms/charts/Calendar3D/index.jsx
  src/components/atoms/charts/ContribRadar/index.jsx
  src/components/atoms/charts/LatestActivity/index.jsx
  src/components/atoms/index.js
Labels: enhancement

#28 Add atoms aa1 to implement 1
  src/components/atoms/Pinned/index.jsx
  src/components/atoms/Pinned/pinned.scss
  src/components/atoms/Project/index.jsx
  src/components/atoms/ScrollToTop/index.jsx
  src/components/atoms/index.js
Labels: enhancement

#29 Add molecules aa1 to implement 1
  package.json
  src/assets/header/dev.svg
  src/assets/header/media.svg
  src/assets/navigation/logo.png
  src/components/molecules/Footer/footer.scss
  src/components/molecules/Footer/index.jsx
  src/components/molecules/Navbar/index.jsx
  src/components/molecules/Navbar/navbar.scss
  src/components/molecules/UserActionCard/index.jsx
  src/components/molecules/UserActionCard/useractioncard.scss
  src/components/molecules/forms/LoginForm/index.jsx
  src/components/molecules/forms/RegisterForm/index.jsx
  src/components/molecules/index.js
  src/components/molecules/modals/UploadModal/index.jsx
Labels: enhancement

#41 Add pages company aa1 to implement 1
  package.json
  src/components/pages/CompanyPage/company.scss
  src/components/pages/CompanyPage/dummy/chart.json
  src/components/pages/CompanyPage/dummy/data.js
  src/components/pages/CompanyPage/index.jsx
  src/components/pages/index.js
Labels: enhancement

#42 Add pages home aa1 to implement 1
  package.json
  src/assets/body/profiles.png
  src/assets/body/ranking.png
  src/assets/body/trophy.png
  src/components/pages/HomePage/homepage.scss
  src/components/pages/HomePage/index.jsx
  src/components/pages/index.js
Labels: enhancement

#43 Add pages profile aa1 to implement 1
  src/components/pages/ProfilePage/index.jsx
  src/components/pages/ProfilePage/profile.scss
  src/components/pages/index.js
Labels: enhancement

#44 Add pages talk aa1 to implement 1
  src/components/pages/TalkPage/index.jsx
  src/components/pages/TalkPage/talk.scss
  src/components/pages/index.js
Labels: enhancement

#49 Add heart aa1 to implement 1
  package.json
  public/index.html
  public/manifest.json
  src/App.js
  src/Routes.js
  src/components/atoms/charts/Calendar3D/index.jsx
  src/components/molecules/Navbar/index.jsx
  src/components/molecules/forms/index.js
  src/components/molecules/modals/SettingsModal/index.jsx
  src/components/molecules/modals/SettingsModal/settings.scss
  src/components/molecules/modals/UploadModal/index.jsx
  src/components/molecules/modals/index.js
  src/components/organisms/profiles/SoftwareEngineer/index.jsx
  src/components/organisms/tabs/TalksTab/index.jsx
  src/components/pages/TalkPage/index.jsx
  src/utilities/_base.scss
  src/utilities/_themes.scss
  src/utilities/_variables.scss
Labels: enhancement

#51 Add search aa1 to implement 1
  package.json
  src/App.js
  src/components/atoms/SearchBar/index.jsx
  src/components/atoms/index.js
  src/components/molecules/Navbar/index.jsx
Labels: enhancement

#63 Improve basics aa1 to implement 1
  .env.template
  package.json
  src/App.js
  src/components/atoms/SearchBar/index.jsx
  src/components/atoms/SearchBar/search.scss
  src/components/organisms/ProfileInfo/index.jsx
  src/components/pages/ProfilePage/index.jsx
  src/index.js
Labels: bug, documentation, enhancement, invalid

#65 Improve basics aa2 to implement 1
  package.json
  public/404.html
  public/CNAME
  public/fav/android-icon-144x144.png
  public/fav/android-icon-192x192.png
  public/fav/android-icon-36x36.png
  public/fav/android-icon-48x48.png
  public/fav/android-icon-72x72.png
  public/fav/android-icon-96x96.png
  public/fav/apple-icon-114x114.png
  public/fav/apple-icon-120x120.png
  public/fav/apple-icon-144x144.png
  public/fav/apple-icon-152x152.png
  public/fav/apple-icon-180x180.png
  public/fav/apple-icon-57x57.png
  public/fav/apple-icon-60x60.png
  public/fav/apple-icon-72x72.png
  public/fav/apple-icon-76x76.png
  public/fav/apple-icon-precomposed.png
  public/fav/apple-icon.png
  public/fav/browserconfig.xml
  public/fav/favicon-16x16.png
  public/fav/favicon-32x32.png
  public/fav/favicon-96x96.png
  public/fav/favicon.ico
  public/fav/manifest.json
  public/fav/ms-icon-144x144.png
  public/fav/ms-icon-150x150.png
  public/fav/ms-icon-310x310.png
  public/fav/ms-icon-70x70.png
  public/index.html
  public/manifest.json
  src/App.js
  src/Routes.js
  src/actions/core.js
  src/actions/index.js
  src/actions/intel/authActions.js
  src/actions/intel/generalActions.js
  src/actions/intel/index.js
  src/actions/intel/talksActions.js
  src/actions/intel/userActions.js
  src/components/atoms/charts/Calendar3D/index.jsx
  src/components/molecules/Navbar/index.jsx
  src/components/molecules/forms/LoginForm/index.jsx
  src/components/molecules/forms/RegisterForm/index.jsx
  src/components/molecules/modals/SettingsModal/index.jsx
  src/components/molecules/modals/UploadModal/index.jsx
  src/components/organisms/ProfileInfo/index.jsx
  src/components/organisms/tabs/TalksTab/index.jsx
  src/components/pages/TalkPage/index.jsx
  src/index.js
Labels: enhancement

#69 Add errorboundary aa1 to implement 1
  src/components/atoms/ErrorBoundary/index.jsx
  src/components/atoms/index.js
  src/components/organisms/tabs/OverviewTab/index.jsx
Labels: enhancement
